[build]
publish = "."
command = "echo 'Static site - no build needed'"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://*.supabase.co https://fonts.googleapis.com https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com https://cdn.jsdelivr.net/npm https://*.supabase.co; connect-src 'self' https://*.supabase.co; img-src 'self' data: blob: https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"

[[headers]]
for = "/**/*.css"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/**/*.js"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/**/*.{png,jpg,jpeg,gif,webp,svg,ico}"

[headers.values]
Cache-Control = "public, max-age=604800"